# .air.toml
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ."
  bin = "tmp/main"
  full_bin = "./tmp/main"

[log]
  time = true

[watch]
  include = ["."]
  exclude = ["tmp", "vendor", "node_modules"]
  extensions = ["go", "tpl", "tmpl", "html"]
